### ISSUE TITLE
请教在服务端上使用不能加载等问题

### ISSUE THREAD

**Issue by Binket** [XiaoYuOvO/FishModLoader#1]
在纯净R196服务端上使用 FishModLoader-B0.1.2 x64 安装完毕后， 加入mod没效果 请问是不支持还是什么原因。

在coremods文件夹里添加【AutoBackup.jar】没效果

found mod AutoBackup.jar
Bad Mod File:D:\[MITE R196]server\coremods\AutoBackup.jar ,mod.json is incorrect

**Comment by XiaoYuOvO** [comment]
这可能是由于使用了旧版本的模组所导致的,请使用新版的模组,并将旧版的模组移除
新版模组下载:
链接：https://pan.baidu.com/s/1VxBssbyd1zHaOV2s65q2dA 
提取码：nomv
